.gitignore
CMakeLists.txt
src/CMakeLists.txt
src/gc_classic_version.H
src/main.F

This new update makes building the project with cmake functional. It removes usage of the copy of HEMCO within GEOS-Chem and instead uses the new HEMCO repository as a git submodule outside of GEOS-Chem. Most updates here are changes in CMake files and I request feedback on the changes. There are CMake updates in GEOS-Chem and HEMCO subprojects as well that I would like to be reviewed as part of this PR.
The updates in this PR appear to be fully functional. However, it appears OMP is not turned on
by default so this is one thing that especially needs attention. I implemented the cmake files to take advantage of code already in GEOS-Chem as much as possible, but perhaps some of that needs to be abstracted out to a higher level. Feedback welcome!

Initial commits to build this repo from source code and run directories

---

CMakeLists.txt
CMakeScripts/FindNetCDF.cmake
CMakeScripts/GC-ConfigureClassic.cmake
CMakeScripts/GC-Helpers.cmake
CMakeScripts/try_compile.F90
src/CMakeLists.txt

This PR moves the old scripts to configure GEOS-Chem Classic to this repo. This does the following
- Builds without a run directory (which was breaking quick-build and build-matrix wheen they included "install" in the build step
- Should be identical to how the old GEOS-Chem Classic build system looked from the users perspective
- Simplifies the build system in the GEOS-Chem repo
There's an accompanying PR for GEOS-Chem:
- https://github.com/geoschem/geos-chem/pull/394

Moved GCC specific build configuration to this repo

---

.ci-pipelines/release.dockerfile
.ci-pipelines/release.yml

- Updated mechanism to use "fullchem" 
- Only "fullchem" is built in the container
- Don't rename the executable with "-standard" suffix
- Changed publishing org to `geoschem`

Updated the release pipeline

---

CMakeLists.txt
CMakeScripts/GC-ConfigureClassic.cmake
CMakeScripts/summarize_build
src/CMakeLists.txt

This PR has two features. Sorry for lumping them, but it was quicker to do it this way. These are pretty trivial changes, but, there is one non-trivial change affecting specialty simulations: when you build GEOS-Chem for a speciality simulation you need to specify which components (e.g. `APM`) should be enabled. However, this change lets us simplify the workflow for the majority of users.
This feature give complete ability to (1) list the compiler options that are used, and (2) fully specify the options you want to use. It does this in a "best-practice" CMake way. This PR provides the mechanism for this, but requires some familiarity with CMake.
Adds the following cache variables:
- GEOSChem_Fortran_FLAGS_<COMPILER_ID> : Compiler flags for all build types for <COMPILER_ID> compiler
- …

Decoupled build directory from the run directory, support for overriding default compiler options

---

CMakeLists.txt

At last weeks GCST telecon, we decided it was okay to have no default value for `RUNDIR`. This PR makes this update.
To achieve the previous behaviour you would do
`cmake /path/to/your/source/code -DRUNDIR=".."`
The purpose of this change is to remove this implicit behaviour because it (1) is no longer necessary to inspect the run directory to configure the build, (2) makes it easier to teach compiling GEOS-Chem since it can be described independent of the run directory, and (3) implies GEOS-Chem needs to be built separately for each run directory. 
This is OK to merge. It's a trival change, but it does affect the build's default behaviour.

No default for RUNDIR

---

CMakeScripts/GC-ConfigureClassic.cmake
src/CMakeLists.txt

@yantosca's integration tests identified that the TOMAS builds were broken following #8.
The issue was that some module in HEMCO need the `-DTOMAS` and `-DTOMAS15` definitions, but #8 decoupled the compiler options of GCClassic and HEMCO, so those HEMCO modules were no longer getting the tomas definitions. This fixes that.
This is OK to merge at any time.

Fixes TOMAS build for GEOS-Chem Classic

---

.gitmodules
docs/Makefile
docs/make.bat
docs/source/conf.py
docs/source/getting-started/quick-start.rst
docs/source/index.rst
docs/source/step-by-step/plotting-output.rst
docs/source/step-by-step/stretched-grid.rst
docs/source/user-guide/compiling.rst
docs/source/user-guide/downloading.rst
docs/source/user-guide/requirements.rst
docs/source/user-guide/rundir-config.rst
docs/source/user-guide/rundir-init.rst
docs/source/user-guide/running.rst

Hi @msulprizio. Here's an initial version of the Sphinx docs for GEOS-Chem Classic. Note that I haven't configured Read the Docs for this, so you'll have to build it locally for now. Let me know when you would like me to set that up (I haven't set up a GEOS-Chem organization).
This should be a nearly identical clone to the GCHP docs template that I set up last night. You can find a live version of those docs here: https://gchp.readthedocs.io/en/latest/. 
**Note**: This uses the RTD theme. Therefore you'll have to `pip install rtd-sphinx-theme`. You can find information about building the docs and useful reST references here: https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/editing_these_docs.html

Added initial template of RTD from GCHP repo

---

CMakeScripts/GC-ConfigureClassic.cmake

The newline characters in the variable being written to the CMakeCache.txt cause a warning. An alternative would be replacing the "\n" characters with "\;".

Removed git macro that gets list of uncommited files

---

.ci-pipelines/build-matrix.yml
.ci-pipelines/quick-build.yml

This PR fixes the quick-build and build-matrix CI pipelines. The pipelines now use the new [geoschem/buildmatrix](https://hub.docker.com/r/geoschem/buildmatrix) images that are generated by [geoschem/BuildMatrixImageGenerator](https://github.com/geoschem/BuildMatrixImageGenerator).
Currently the build matrix covers GCC 8, 9, and 10. I will build and push images for 6 and 7 when I have a chance (they're easy to add to build-matrix once they're on DockerHub).
This PR can be merged immediately.

Update CI tests to use the new geoschem/buildmatrix images.

---

.github/workflows/cloud-benchmarking-workflow.yml

This PR creates a github action which:
- triggers a 1Day benchmark for commits and prs to dev
- triggers a 1Month benchmark for newly created tags
Currently the cloud benchmark will kick off with Spot instances. We may need to revisit whether to use on demand instances for the 1Month benchmarks

Feature: Github action for triggering cloud benchmarks

---

docs/source/supplement/spack.rst

Simplify the setup instructions by using "spack compiler find" instead of manually editing the compilers.yaml file.

Simplify Spack compiler setup with "spack compiler find"

---

.github/workflows/cloud-benchmarking-workflow.yml

This PR updates the github action for triggering benchmarks on aws. The updates include:
- Updating the workflow commits to set off 1Hr runs instead of 1Day
- bumping up the amount of memory. As the new appears to have greater memory requirements.
- updating to use the shortened commit hash for legibility

Feature/benchmarking updates: trigger 1Hr runs and use short commit hash

---

CHANGELOG.md

This PR adds `CHANGELOG.md` to the GCClassic repository. This file follows the format outlined at https://keepachangelog.com/en/1.0.0/. It also only documents changes in the GCClassic wrapper and instructs users to view CHANGELOG.md files in the submodules for changes there.

[PULL REQUEST] Add CHANGELOG.md

---

.github/workflows/findRefKey.sh

This update uses the git describe `--exclude` flag to find primary keys to reconcile commit annotations with recent tags.
See also GCHP PR at https://github.com/geoschem/GCHP/pull/280.

bugfix/findRefKey: update findRefKey.sh to find previous commits

---

CMakeScripts/GC-ConfigureClassic.cmake

This is the GCClassic superproject PR corresponding to https://github.com/geoschem/geos-chem/pull/1605. It supersedes https://github.com/geoschem/GCClassic/pull/30.
Note: This PR only includes updates to the superproject and does not commit updates to the GEOS-Chem submodule, as is now the preferred method for superproject PRs.

Add carbon simulation and KPP mechanism

---

.github/ISSUE_TEMPLATE/config.yml
.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md

This PR fixes some problems with the GitHub issue and PR templates. Namely:
1. The PR template is now `.github/PULL_REQUEST_TEMPLATE.md`
2. Added `.github/ISSUE_TEMPLATE/config.yml` to prevent blank issues and add a link to the GC manual at RTD.
This is a zero-diff update, as only code in the .github folder was touched.

Fix problems with GitHub issue and PR templates

---

CMakeLists.txt

Name: Melissa Sulprizio
Institution: Harvard/GCST
As discussed in #38, the GEOSChem_Fortran_FLAGS_DEBUG_Intel option was missing a "-" before the "g" compile option. This pull request fixes that typo.
This fix will avoid a compile error with ifort.
Closes #38

Fix typo in Intel debug option in CMakeLists.txt

---

CHANGELOG.md
test

This is a companion PR to https://github.com/geoschem/geos-chem/pull/1794.  This resets the `test` folder to the new path `src/GEOS-Chem/test` to be consistent with the changes made in the geoschem/geos-chem repo.
This is a zero-diff update, as it only modifies a symbolic link.  No scientific changes are added.
N/A
- Merge after https://github.com/geoschem/geos-chem/pull/1794
- Fixes several issues in https://github.com/geoschem/geos-chem/issues/714
- The corresponding PR for GCHP is https://github.com/geoschem/GCHP/pull/327
Please link to the corresponding Github issue here. If fixing a bug, there should be an issue describing it with steps to reproduce.

Update symbolic link from GCClassic root folder to the test folder

---

.gitmodules
CHANGELOG.md
CMakeLists.txt
CMakeScripts/GC-ConfigureClassic.cmake
CMakeScripts/summarize_build
src/CMakeLists.txt

Name: Lizzie Lundgren
Institution: Harvard University
This update adds the [Cloud-J](https://github.com/geoschem/cloud-J/) photolysis library as a submodule with GC-Classic. It is stored alongside GEOS-Chem and HEMCO in the `src` folder. This PR should be merged with https://github.com/geoschem/geos-chem/pull/1522.
See https://github.com/geoschem/geos-chem/pull/1522 for changes expected in GEOS-Chem when using Cloud-J to compute J-values.
Prather, M. J.: Photolysis rates in correlated overlapping cloud fields: Cloud-J 7.3c, Geosci. Model Dev., 8, 2587–2595, https://doi.org/10.5194/gmd-8-2587-2015, 2015.
https://github.com/geoschem/geos-chem/pull/1522

Cloud-J in GEOS-Chem Classic

---

CHANGELOG.md
CMakeScripts/GC-ConfigureClassic.cmake
docs/source/gcclassic-user-guide/compile-cmake.rst

This PR is the companion to https://github.com/geoschem/geos-chem/pull/2166.  It removes the `BPCH_DIAG` CMake configuration option from `CMakeScripts/GC-ConfigureClassic.cmake`.
This is a zero-diff update.  It does not contain any submodule hashes.  It should be merged into dev/14.4.0 following https://github.com/geoschem/geos-chem/pull/2166.
- https://github.com/geoschem/geos-chem/pull/2166
- https://github.com/geoschem/geos-chem/issues/82

Removed BPCH_DIAG compilation option

---

.gitmodules
CHANGELOG.md

This is a minor update that fixes some incorrect submodule names in the `.gitmodules` file.  We have changed:
```console
[submodule "src/GEOS-Chem"]
[submodule "src/HEMCO"]
[submodule "docs/source/geos-chem-shared-docs"]
[submodule "src/GEOS-Chem/Cloud-J"]
```
to
```console
[submodule "GEOS-Chem"]
[submodule "HEMCO"]
[submodule "geos-chem-shared-docs"]
[submodule "Cloud-J"]
```
This is a zero-diff update.
NOTE: This PR should be merged immediately after:
- https://github.com/geoschem/geos-chem/pull/2154
- https://github.com/geoschem/cloud-j/pull/2

Now use short submodule names in .gitmodules

---

.github/workflows/gcclassic-compile-tests.yml
CHANGELOG.md

This PR adds a GitHub Action to invoke a compilation-only integration test every time a pull request or push is made to this repository.  
NOTE: This PR does not contain any submodule hashes.  It should be merged after https://github.com/geoschem/geos-chem/pull/2187 is merged into `dev/no-diff-to-benchmark` branch.
This is a zero-diff update.  It will cause compile-only integration tests for GCClassic to be run.
- See https://github.com/geoschem/geos-chem/pull/2187

Add GitHub action for compile-only integration tests

---

CHANGELOG.md
docs/source/gcclassic-user-guide/geoschem-config.rst

Name: Melissa Sulprizio
Institution: Harvard
In pull request https://github.com/geoschem/geos-chem/pull/2218 several options were retired from the CH4 menu in geoschem_config.rc. These options were removed in favor of handling emissions perturbations and scale factors directly in HEMCO_Config.rc.
This should be merged alongside:
- https://github.com/geoschem/geos-chem/pull/2218

Remove obsolete options from CH4 menu in geoschem-config.rst

---

.gitmodules
CHANGELOG.md
CMakeLists.txt
src/CMakeLists.txt

Name: Lizzie Lundgren
Institution: Harvard University
This PR adds the ISOROPPIA II aerosol thermodynamics package with [HETPv1.0](https://github.com/geoschem/HETerogeneous-vectorized-or-Parallel) as a new git submodule. From the HETP README:
> HETP is an aerosol thermodynamic equilibrium solver written in modern Fortran based on ISORROPIA II (which is written in FORTRAN 77).  HETP solves only the 'forward' metastable state of the NH4+/Na+/Ca2+/K+/Mg2+/SO42–/NO3–/Cl–/H2O system.  The main publication for HETP is avaiable online at:  https://gmd.copernicus.org/preprints/gmd-2023-159/.
Note that this PR can be merged prior to updates in GEOS-Chem to use HETP without issue. However, it is required before the updates to GEOS-Chem in PR https://github.com/geoschem/geos-chem/pull/2244. …

New submodule: HETP aerosol thermodynamics

---

CHANGELOG.md
CMakeScripts/GC-ConfigureClassic.cmake

This PR adds an error trap that causes CMake to throw an error if the FASTJX compile option is selected for any mechanism except Hg.
Configuring with the `-DFASTJX=y` option now throws an error message such as:
```console
CMake Error: The source directory "/n/holyscratch01/jacob_lab/ryantosca/tests/nodiff/gc237x/test_fullchem" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
[holy8a24501 build]$ cmake ../CodeDir -DFASTJX=y
-- The Fortran compiler identification is GNU 10.2.0
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /n/sw/helmod-rocky8/apps/Core/gcc/10.2.0-fasrc01/bin/gfortran - skipped …
```

Throw a CMake error if FAST-JX is used for any KPP mechanism except Hg

---

CHANGELOG.md
docs/source/gcclassic-user-guide/geoschem-config.rst

Name: Nick Balasus
Institution: Harvard University
Describe latitude and longitude bounds in `geoschem_config.yml` as grid cell edges instead of centers.
n/a
n/a
https://github.com/geoschem/geos-chem/issues/2411

update latitude and longitude bounds description

---

CHANGELOG.md
src/CMakeLists.txt

This PR brings the updates that were formerly in geos-chem PR #2382 and geos-chem PR #2383 into the dev/no-diff-to-benchmark branch. These will ship in 14.5.1.  It modifies the `src/CMakeLists.txt` file to build the KPP standalone file when compiled with `-DMECH=fullchem` or `-DMECH=custom`.
This is a zero-diff update
If this is a science update, please provide a literature citation.
- https://github.com/geoschem/geos-chem/pull/2588
- https://github.com/geoschem/GCHP/pull/463
- https://github.com/geoschem/geos-chem/pull/2482
- https://github.com/geoschem/geos-chem/pull/2483

Add KPP standalone model to GEOS-Chem 14.5.1

---

.ci-pipelines/build-matrix.yml
.ci-pipelines/quick-build.yml
CHANGELOG.md

This PR resolves the following error:
```console
=================================================================
GEOS-Chem 14.5.0 (science codebase)
Current status: 14.6.0-alpha.0-84-g990e8e408
=================================================================
CMake Error at src/GEOS-Chem/KPP/CMakeLists.txt:9 (add_subdirectory):
The source directory
/__w/1/s/src/GEOS-Chem/KPP/standalone
does not contain a CMakeLists.txt file.
Creating /__w/1/s/src/GEOS-Chem/Interfaces/GCClassic/gc_classic_version.H
-- Configuring incomplete, errors occurred!
See also "/__w/1/s/build/CMakeFiles/CMakeOutput.log".
+ make -j
make: *** No targets specified and no makefile found.  Stop.
```
in GEOS-Chem Classic continuous integration tests on Azure Dev Pipelines. …

Fix configuration error in GEOS-Chem Classic continuous integration tests on Azure

---

CHANGELOG.md
src/CMakeLists.txt

This PR fixes the error described by @msulprizio in #78.  We have reworked the logic in the CMakeLists.txt to disable building the KPP standalone executable for simulations other than fullchem & custom, even if the CMake commands are given separately.
These commands now configure GEOS-Chem Classic correctly:
```console
cmake ../CodeDir
cmake . -DMECH=custom -DRUNDIR=..
```
- Closes #78
- https://github.com/geoschem/GCHP/pull/464

Fixed error in CMake logic that attempted to build the KPP standalone for mechanisms other than fullchem and custom

---

CHANGELOG.md
docs/requirements.txt

We have updated the version of jinja2 (needed for ReadTheDocs) from 3.1.4 to 3.1.5, to fix a security issue.  This was suggested by the GitHub Dependabot service.
This is a zero-diff update.  It only affects the Python packages used for ReadTheDocs.

Bump jinja2 to 3.1.5 as suggested by Dependabot

---

CHANGELOG.md
CMakeScripts/GC-ConfigureClassic.cmake
src/CMakeLists.txt

This PR adds CMake updates so that the KPP-Standalone executable will not be built unless the user configures with the `-DKPPSA=y` option.
This is a zero-diff update 
- Must be merged with https://github.com/geoschem/geos-chem/pull/2712

Do not build KPP-Standalone executable unless specifically requested at compile time

---

CHANGELOG.md
CMakeLists.txt
docs/source/conf.py

This PR seeks to merge the release/14.6.2 branch into main in anticipation of the GCClassic 14.6.2 release.
The release/14.6.2 branch contains
- Commits from the dev/no-diff-to-benchmark branch
- Documentation updates from the docs/dev branch.
- Updated version numbers to 14.6.2 in the usual places.
- Updated GEOS-Chem submodule to version 14.6.2

GCClassic 14.6.2 release

---

CHANGELOG.md
CMakeLists.txt

This PR adds the `-DDEBUG` option to the list of compiler flags that get selected when `-DCMAKE_BUILD_TYPE=Debug`.  This can be used to toggle warning statements or other code that should only execute when the GEOS-Chem Classic is built with the debugging flags turned on.
This is a no-diff-to-benchmark update.
- Should have been merged alongside [geos-chem #2915](https://github.com/geoschem/geos-chem/pull/2915) but wasn't

Add -DDEBUG to Intel and GNU debug compiler flags
